apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-dev.fullname" . }}
  labels:
    {{- include "minio-dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: minio
      protocol: TCP
      name: minio
  selector:
    {{- include "minio-dev.selectorLabels" . | nindent 4 }}
