---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: {{ .Values.approval_strategy }}
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
...
