---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressgateway-cert
spec:
  # Secret names are always required.
  secretName: ingressgateway-cert
  commonName: {{ .Values.ingressgateway.cert.commonName }}
  usages:
    - server auth
    - client auth  
  issuerRef:
    name: mycompany-intermediaryca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    # group: cert-manager.io
...
