kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-anyuid
subjects:
  - kind: ServiceAccount
    name: redis
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
