apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oracledb-free.fullname" . }}-scripts
  labels:
    {{- include "oracledb-free.labels" . | nindent 4 }}
data:
  configTcps.sh: |
    {{- .Values.scripts.configTcps | nindent 4 }}
