apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oracledb-free.fullname" . }}-oradata
  labels:
    {{- include "oracledb-free.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
