apiVersion: v1
kind: Service
metadata:
  name: oracledb-nodeport
  labels:
    {{- include "oracledb-free.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: oracle-listener
      protocol: TCP
      name: listener
    - port: 6666
      targetPort: tcps
      protocol: TCP
      name: tcps
  selector:
    {{- include "oracledb-free.selectorLabels" . | nindent 4 }}
