---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bookinfo
  namespace: {{ .Values.ingressgateway.namespace }}
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
...
