---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-echo-headers
spec:
  gateways:
  - {{ .Values.ingressgateway.namespace }}/nginx-echo-headers
  hosts:
  - {{ .Values.ingressgateway.host }}
  http:
  - route:
    - destination:
        host: nginx-echo-headers.nginx-echo-headers.svc.cluster.local
        port:
          number: 8080
...