apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshift-oauth-proxy.fullname" . }}
  labels:
    {{- include "openshift-oauth-proxy.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "openshift-oauth-proxy.fullname" . }}-tls
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "openshift-oauth-proxy.selectorLabels" . | nindent 4 }}
