apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: golang-ex
spec:
  host: golang-ex.golang-ex.svc.cluster.local
  subsets:
  - name: v1
    labels:
      app.kubernetes.io/instance: golang-ex
  - name: v2
    labels:
      app.kubernetes.io/instance: golang-ex-v2
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
