apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-oracledb
spec:
  host: {{ .Values.oracledb.host }}
  subsets:
  - name: oracle-tls
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: {{ .Values.oracledb.port }}
        tls:
          mode: SIMPLE # only works for HTTP
