apiVersion: constraints.gatekeeper.sh/v1beta1
kind: UniqueVserviceHostname
metadata:
  name: vs-same-host-constraint
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups:
          - networking.istio.io
        kinds:
          - VirtualService
    namespaceSelector:
      matchLabels:
        maistra.io/member-of: istio-system
