kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-query-frontend
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
