apiVersion: v1
kind: Secret
metadata:
  name: minio-dev
stringData:
  endpoint: http://minio.minio-tenant.svc.cluster.local:80
  bucket: tempo
  access_key_id: tempo
  access_key_secret: tempotempo
type: Opaque
