apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: minio-dev
spec:
  storageSize: 1Gi
  storage: 
    secret:
      name: minio-dev
      type: s3
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  # observability:
  #   metrics:
  #     createServiceMonitors: true
  # observability:
  #   metrics:
  #     createPrometheusRules: true
  template:
    queryFrontend:
      jaegerQuery: 
        enabled: true
        ingress:
          route:
            termination: edge
          type: route