---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ include "gateway.name" . }}
    weight: 100
  wildcardPolicy: None
...
