---
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneRef:
    name: {{ .Values.control_plane_name }}
    namespace: {{ .Values.control_plane_namespace }}
...