apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-mysqldb-through-egress-gateway
spec:
  hosts:
  - {{ .Values.mysqldb.host }}
  gateways:
  - mesh
  - istio-egress/mysqldb
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - {{ .Values.mysqldb.ip }}/32
      port: {{ .Values.mysqldb.port }}
    route:
    - destination:
        host: {{ .Values.gateways.egress.host }}
        subset: mysql-mtls
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egress/mysqldb
      port: 443
    route:
    - destination:
        host: {{ .Values.mysqldb.host }}
        subset: mysql-tls
        port:
          number: {{ .Values.mysqldb.port }}
      weight: 100
