kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kiali-prometheus-monitoring-exporter-istio-system
subjects:
  - kind: ServiceAccount
    name: kiali-service-account
    namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-monitoring-exporter-istio-system
