apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/version: 2.4.1-1-7
    app.kubernetes.io/component: kiali
    app.kubernetes.io/name: kiali
spec:
  api:
    namespaces:
      exclude:
      - "^istio-operator"
      - "^kube-.*"
      - "^openshift.*"
      - "^ibm.*"
      - "^kiali-operator"
      label_selector_include: "istio.io/rev=ossm-2.5"
  auth:
    strategy: openshift
  deployment:
    cluster_wide_access: true
    image_pull_policy: ''
    ingress:
      enabled: true
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: 'false'
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    logger:
      log_level: debug
  external_services:
    custom_dashboards:
      namespace_label: kubernetes_namespace
    grafana:
      auth:
        password: {{ .Values.htpasswd }}
        type: none
        use_kiali_token: false
        username: internal
      enabled: true
      in_cluster_url: 'http://grafana-instance-service.istio-system.svc:3000'
      url: {{ .Values.kiali.grafana.url }}
    istio:
      config_map_name: istio-full-install
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-full-install
      istiod_deployment_name: istiod-full-install
      url_service_version: 'http://istiod-full-install.istio-system:15014/version'
    prometheus:
      auth:
        insecure_skip_verify: true
        type: bearer
        use_kiali_token: true
      query_scope:
        mesh_id: istio-system/full-install
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    tracing:
      query_timeout: 30
      enabled: true
      in_cluster_url: 'http://tempo-minio-dev-query-frontend.tempo-system.svc.cluster.local:16685'
      url: {{ .Values.kiali.tempo.url }}
      use_grpc: true
  installation_tag: 'Kiali [istio-system]'
  istio_namespace: istio-system
  version: default
