apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ossmconsole-components-to-kiali
  namespace: istio-system
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-console
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-operators
  podSelector:
    matchLabels:
      app: kiali
  policyTypes:
  - Ingress
