apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
spec:
  tracing:
  - providers:
    - name: tempo
    randomSamplingPercentage: 100
  metrics:
  - providers:
    - name: prometheus
