kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
  namespace: minio-operator
spec:
  to:
    kind: Service
    name: console
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
  wildcardPolicy: None
