apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mysql-persistent.fullname" . }}-cert
spec:
  # Secret names are always required.
  secretName: {{ include "mysql-persistent.fullname" . }}-cert
  commonName: {{ include "mysql-persistent.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
    - {{ include "mysql-persistent.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  usages:
    - server auth
    - client auth  
  issuerRef:
    kind: ClusterIssuer
    name: mycompany-intermediaryca-issuer
