apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-persistent.fullname" . }}-nodeport
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "mysql-persistent.selectorLabels" . | nindent 4 }}
