apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-persistent.fullname" . }}
  labels:
    {{- include "mysql-persistent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "mysql-persistent.selectorLabels" . | nindent 4 }}
