{{- range $k, $v := .Values.features }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.context.name }}-{{ $k }}
  namespace: {{ $.Values.ingressgateway.namespace }}
spec:
  host: {{ $v.host }}
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
...
{{- end }}
