---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "golang-ex-istio.fullname" . }}
  namespace: {{ .Values.ingressgateway.namespace }}
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
...
