apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sql.fullname" . }}
  labels:
    {{- include "sql.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: keystore
        image: registry.access.redhat.com/ubi9/openjdk-11:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
        args:
          - '-c'
          - >-
            keytool -importkeystore -srckeystore ${JAVA_HOME}/lib/security/cacerts -srcstoretype JKS -destkeystore /keystore/truststore.jks -storepass changeit -srcstorepass changeit &&
            keytool -import -alias oracledb-free -trustcacerts -keystore /keystore/truststore.jks -file /secrets/ca.crt -storepass changeit -noprompt &&
            keytool -list -keystore /keystore/truststore.jks -storepass changeit | grep oracledb-free
        volumeMounts:
          - mountPath: /secrets
            name: p12-cert
          - mountPath: /keystore
            name: keystore
      containers:
        - name: {{ .Chart.Name }}
          stdin: true
          command:
            - tail
            - -f
            - /dev/null
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Djavax.net.ssl.trustStore=/keystore/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /keystore
              name: keystore
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: p12-cert
          secret:
            secretName: secure-oracledb-free-p12-cert
        - emptyDir: {}
          name: keystore
