kind: ConfigMap
apiVersion: v1
metadata:
  name: oracle-network
data:
  listener.ora: >
    # listener.ora Network Configuration File:
            
    SID_LIST_LISTENER = 
      (SID_LIST =
        (SID_DESC =
          (SID_NAME = PLSExtProc)
          (ORACLE_HOME = /opt/oracle/product/23c/dbhomeFree)
          (PROGRAM = extproc)
        )
      )

    LISTENER =
      (DESCRIPTION_LIST =
        (DESCRIPTION =
          (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_FREE))
          (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
          (ADDRESS = (PROTOCOL = TCPS)(HOST = 0.0.0.0)(PORT = 2484))
        )
      )

    DEFAULT_SERVICE_LISTENER = (FREE))

    WALLET_LOCATION = (SOURCE = (METHOD = FILE)(METHOD_DATA = (DIRECTORY =
    /opt/oracle/oradata/dbconfig/FREE/.tls-wallet)))

    SSL_CLIENT_AUTHENTICATION = FALSE
  sqlnet.ora: >
    NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT, HOSTNAME)

    DISABLE_OOB=ON

    WALLET_LOCATION = (SOURCE = (METHOD = FILE)(METHOD_DATA = (DIRECTORY =
    /opt/oracle/oradata/dbconfig/FREE/.tls-wallet)))

    SSL_CLIENT_AUTHENTICATION = FALSE
  tnsnames.ora: |
    # tnsnames.ora Network Configuration File:

    FREE =
      (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
        (CONNECT_DATA =
          (SERVER = DEDICATED)
          (SERVICE_NAME = FREE)
        )
      )

    LISTENER_FREE =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))

    FREEPDB1 =
      (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
        (CONNECT_DATA =
          (SERVER = DEDICATED)
          (SERVICE_NAME = FREEPDB1)
        )
      )

    EXTPROC_CONNECTION_DATA =
      (DESCRIPTION =
        (ADDRESS_LIST =
          (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_FREE))
        )
        (CONNECT_DATA =
          (SID = PLSExtProc)
          (PRESENTATION = RO)
        )
      )
