apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-for-tempo
spec:
  host: tempo-minio-dev-distributor.tempo-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
