apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-for-tempo
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-2"
spec:
  host: tempo-minio-dev-distributor.tempo-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
