apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: tempo-otlp-http
spec:
  hosts:
  - tempo-minio-dev-distributor.tempo-system.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - number: 4317
    name: otlp-grpc
    protocol: GRPC
  resolution: DNS
