---
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace: tempo-dev
spec:
  controlPlaneRef:
    name: {{ .Values.smcp.name }}
    namespace: {{ .Values.smcp.namespace }}
...