apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mongodb
  namespace: istio-egress
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - {{ .Values.mongodb.host }}
    tls:
      mode: ISTIO_MUTUAL
