apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-mongodb-through-egress-gateway
spec:
  hosts:
  - {{ .Values.mongodb.host }}
  gateways:
  - mesh
  - istio-egress/mongodb
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - {{ .Values.mongodb.ip }}/32
      port: {{ .Values.mongodb.port }}
    route:
    - destination:
        host: {{ .Values.gateways.egress.host }}
        subset: mongo-mtls
        port:
          number: 443
      weight: 100
  - match:
    - gateways:
      - istio-egress/mongodb
      port: 443
    route:
    - destination:
        host: {{ .Values.mongodb.host }}
        subset: mongo-tls
        port:
          number: {{ .Values.mongodb.port }}
      weight: 100
