apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-ex.fullname" . }}
  labels:
    {{- include "golang-ex.labels" . | nindent 4 }}
    app: golang-ex-{{ .Values.version }}
    service: golang-ex-{{ .Values.version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "golang-ex.selectorLabels" . | nindent 4 }}
